### ISSUE TITLE
Consider adding a "slider" hint for "number", "integer", and "percentage" types

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/GraphicsDataDefinition#4]
Sometimes, numeric inputs are best represented as an input field, other times they are best represented as a slider. It would be neat if there was a way to have a "hint" that one of these properties should be represented as a slider instead of an input field. This could be a progressive enhancement that gracefully falls back to an input field if the UI in question doesn't support sliders.

Use of a slider would require the presence of minimum and maximum values.

**Comment by nytamin** [comment]
Agreed, in the generic sense I think this should be up to the GUI to decide (using the minimum/maximum properties as hints) or a separate GDDType for a specific type of input
