### ISSUE TITLE
Consider supporting default values

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/GraphicsDataDefinition#5]
Some parameters of graphics may need to have a default value. Some examples may be the volume level of a sound, the URL of a remote resource/API endpoint, boolean toggles for things like showing/hiding elements of a graphic, etc. JSON Schema supports a `default` field that could be used for this. The use of default values could take one of two forms:

1. Use the existing `default` keyword from the current JSON Schema standard:

```json
{
  "title": "One-Line GFX Template",
  "type": "object",
  "properties": {
    "text0": {
      "description": "Text content",
      "type": "string",
      "gddType": ["single-line"],
      "gddOptions": {
        "maxLength": 50
      }
    }
  },
  "required": ["text0"],
  "default": {
    "text0": "Foo"
  }
}
```

The downside of this approach is that the default values aren't defined in the same place as the properties, which is a bit messy.

2. Add an optional `gddDefault` field to property definitions:

```json
{
  "title": "One-Line GFX Template",
  "type": "object",
  "properties": {
    "text0": {
      "description": "Text content",
      "type": "string",
      "gddType": ["single-line"],
      "gddOptions": {
        "maxLength": 50
      },
      "gddDefault": "Foo"
    }
  },
  "required": ["text0"]
}
```

The downside of this approach is that it is non-standard when a standard exists that could be used.

**Comment by jstarpl** [comment]
I definitely would vote for going for _Option 1_, since it's reusing an existing, established standard. I think whatever mess this adds will be overcome by JSON Schema support in IDEs through code hints and instant validation.

**Comment by nytamin** [comment]
I am all for Option 1, we should reuse JSON-schema standard properties whenever we can.

This would put another requirement for GUI-implementations though (need to create the initial data-object by traversing the schema), but I think that is reasonable
