### ISSUE TITLE
Consider a standard for allowing partial data updates

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/GraphicsDataDefinition#8]
Say you've got a huge monographic with dozens of GDD properties. The operator might not want to send a full update for every change they make in the UI. This ties into #7 in the use case of multiple operators. Partial data updates might look like the following:

```js
let text0 = 'Foo'
let text1 = 'Bar'

function update(data) {
  if ('text0' in data) {
    text0 = data.text0
  }

  if ('text1' in data) {
    text1 = data.text1
  }
}
```

**Comment by ianshade** [comment]
Deep updates would be nice too. If the dot was reserved, you could send (to a template that specifies that it supports this feature) for example the following data:
```json
{
    "people.0.name": "Johan"
}
```
I think that comes with less challenges than sending incomplete objects like:
```json
{
    "people": [{
        "name": "Johan"
    }]
}
```

**Comment by alvancamp** [comment]
Closing for now as out-of-scope. This will be up to individual implementations.
